Repository geopython/pycsw, pull requests merged in 2024-08, with the labels that each got.

#986 set GetRecords results returned to 0 when resulttype = hits
  pycsw/ogc/csw/csw2.py
  tests/functionaltests/suites/default/expected/get_GetRecords-all.xml
  tests/functionaltests/suites/default/expected/get_GetRecords-empty-maxrecords.xml
  tests/functionaltests/suites/default/expected/post_GetRecords-all-resulttype-hits.xml
Labels: bug

#988 update to latest OGC API - Records specification
  .github/workflows/main.yml
  .github/workflows/vulnerabilities.yml
  pycsw/core/repository.py
  pycsw/ogc/api/records.py
  pycsw/ogc/api/util.py
  pycsw/ogc/gml/gml3.py
  requirements.txt
  tests/functionaltests/suites/oarec/test_oarec_functional.py
  tox.ini
Labels: enhancement, bug, OGC API - Records

#991 minor STAC API updates
  pycsw/core/metadata.py
  pycsw/ogc/api/records.py
  pycsw/ogc/api/util.py
  pycsw/stac/api.py
  tests/functionaltests/suites/stac_api/test_stac_api_functional.py
Labels: enhancement, STAC API

#992 safeguard JSON parsing (#982)
  pycsw/core/metadata.py
Labels: bug

#993 remove Paver utilities not needed
  CONTRIBUTING.rst
  docs/locale/zh/LC_MESSAGES/contributing.po
  docs/locale/zh/LC_MESSAGES/testing.po
  docs/testing.rst
  pavement.py
  requirements-dev.txt
Labels: enhancement

#999 update tests docs, align with code
  docs/testing.rst
Labels: docs

#1003 fix docker/compose/pycsw.yml (fixes #1002)
  docker/compose/pycsw.yml
Labels: bug
